server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    #gateway
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
      #路由的ID，命名最好可以配合服务名
      - id: payment_routh1
        #匹配后提供服务的路由地址
        #uri: http://localhost:8001

        #匹配后提供服务的路由地址
        uri: lb://cloud-payment-service
        #断言，路径相匹配的进行路由
        predicates:
        - Path=/payment/get/**

      - id: payment_routh2
        #uri: http://localhost:8001

        uri: lb://cloud-payment-service
        predicates:
        - Path=/payment/lb/**

        #在此时间之后
        - After=2020-07-04T13:00:00.000+08:00[Asia/Shanghai]

        #在此时间之前
        #- Before=2020-07-05T13:00:00.000+08:00[Asia/Shanghai]

        #在此时间之间
        #- Between=2020-07-04T13:00:00.000+08:00[Asia/Shanghai],2020-07-05T13:00:00.000+08:00[Asia/Shanghai]

        #Cookie
        #- Cookie=username,springcloud

        #Header 请求头要有X-Request-Id属性并且值为正整数的正则表达式
        #- Header=X-Request-Id, \d+

        #Host
        #- Host=**.hry.com

        #Method  GET和POST
        #- Method=POST

        #Query  要有参数username并且值还是正整数  访问时?username=123
        #- Query=username, \d+




eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #单机版
      defaultZone: http://eureka7001.com:7001/eureka/
      #集群版
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/