server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:1111 #换成Nginx的1111端口，做集群
        #server-addr: localhost:8848 #配置nacos地址

management:
  endpoints:
    web:
      exposure:
        include: "*"